EmlakProjesi/Controllers/IsyerisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EmlakProjesi.Models;

namespace EmlakProjesi.Controllers
{
    public class IsyerisController : Controller
    {
        private readonly EmlakDbContext _context;

        public IsyerisController(EmlakDbContext context)
        {
            _context = context;
        }

        // GET: Isyeris
        public async Task<IActionResult> Index()
        {
            return View(await _context.Isyeri.ToListAsync());
        }

        // GET: Isyeris/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var isyeri = await _context.Isyeri
                .FirstOrDefaultAsync(m => m.IsyeriId == id);
            if (isyeri == null)
            {
                return NotFound();
            }

            return View(isyeri);
        }

        // GET: Isyeris/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Isyeris/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IsyeriId,IsletmeAdi,Adres,PhoneNumber,YetkiliAdi")] Isyeri isyeri)
        {

            if (ModelState.IsValid)
            {
                _context.Add(isyeri);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(isyeri);
        }

        // GET: Isyeris/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var isyeri = await _context.Isyeri.FindAsync(id);
            if (isyeri == null)
            {
                return NotFound();
            }
            return View(isyeri);
        }

        // POST: Isyeris/Edit/5 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("IsyeriId,IsletmeAdi,Adres,PhoneNumber,YetkiliAdi")] Isyeri isyeri)
        {
            if (id != isyeri.IsyeriId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(isyeri);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IsyeriExists(isyeri.IsyeriId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(isyeri);
        }


        private bool IsyeriExists(long id)
        {
            return _context.Isyeri.Any(e => e.IsyeriId == id);
        }
    }
}

EmlakProjesi/Views/Shared/_Header.cshtml
<div class="header bg-gradient-primary pb-8 pt-5 pt-md-6">
    <div class="container-fluid">
        <div class="header-body">
            <!-- Card stats -->

        </div>
    </div>
</div>

EmlakProjesi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <partial name="_PageHeadElement" />

    @RenderSection("Styles", required: false)
    @RenderSection("HeadScripts", required: false)
</head>
<body>

    <partial name="_Sidebar" />
    <div class="main-content">
        <partial name="_Navbar" />
        <partial name="_Header" />
        <!-- Page content -->
        <div class="container-fluid mt--6" style="padding:100px">
            <!-- Page content -->
            @RenderBody()
        </div>
    </div>

    <partial name="_ThemeScripts" />

    @RenderSection("Scripts", required: false)
</body>
</html>

EmlakProjesi/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
    <div class="container-fluid">
        <!-- Form -->
        <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block">Emlak Admin Paneli</a>
        <form class="navbar-search navbar-search-dark form-inline mr-3 d-none d-md-flex ml-lg-auto">
            <div class="form-group mb-0">
                <div class="input-group input-group-alternative">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-search"></i></span>
                    </div>
                    <input class="form-control" placeholder="Search" type="text">
                </div>
            </div>
        </form>
    </div>
</nav>

EmlakProjesi/Views/Shared/_PageHeadElement.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
<title>@ViewData["Title"] | Unreal Real Estates-Gerçek Üstü Emlak Admin Panel</title>
<!-- Favicon -->
<link href="~/img/brand/unreal.png" rel="icon" type="image/png">


<partial name="_ThemeStyles" />

EmlakProjesi/Views/Shared/_Sidebar.cshtml
<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Brand -->
        <a class="navbar-brand pt-0" href="/">
            <img src="~/img/brand/unreal.png" class="navbar-brand-img" style="max-height:6rem;" alt="...">
        </a>
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <!-- Collapse header -->
            <div class="navbar-collapse-header d-md-none">
                <div class="row">
                    <div class="col-6 collapse-brand">
                        <a href="./index">
                            <img src="~/img/brand/unreal.png" style="max-height:6rem;">
                        </a>
                    </div>
                    <div class="col-6 collapse-close">
                        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                </div>
            </div>
            <!-- Form -->
            <form class="mt-4 mb-3 d-md-none">
                <div class="input-group input-group-rounded input-group-merge">
                    <input type="search" class="form-control form-control-rounded form-control-prepended" placeholder="Search" aria-label="Search">
                    <div class="input-group-prepend">
                        <div class="input-group-text">
                            <span class="fa fa-search"></span>
                        </div>
                    </div>
                </div>
            </form>
            <!-- Navigation -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Isyeris" asp-action="Index">
                        <i class="ni ni-briefcase-24 text-primary"></i> İş Yerleri
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/musteri">
                        <i class="ni ni-single-02 text-yellow"></i> Müşteriler
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/konut">
                        <i class="ni ni-building text-blue"></i> Konutlar
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

EmlakProjesi/Views/Shared/_ThemeScripts.cshtml
<!-- Core -->
<script src="~/vendor/jquery/dist/jquery.min.js" asp-append-version="true"></script>
<script src="~/vendor/bootstrap/dist/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
<!-- Docs JS -->
<script src="~/vendor/anchor-js/anchor.min.js" asp-append-version="true"></script>
<script src="~/vendor/clipboard/dist/clipboard.min.js" asp-append-version="true"></script>
<script src="~/vendor/holderjs/holder.min.js" asp-append-version="true"></script>
<script src="~/vendor/prismjs/prism.js" asp-append-version="true"></script>
<!-- Optional JS -->
<script src="~/vendor/chart.js/dist/Chart.min.js" asp-append-version="true"></script>
<script src="~/vendor/chart.js/dist/Chart.extension.js" asp-append-version="true"></script>
<script src="~/vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js" asp-append-version="true"></script>
<!-- Argon JS -->
<script src="~/js/argon.min.js" asp-append-version="true"></script>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
<script src="~/js/jquery.inputmask.bundle.js"></script> 

EmlakProjesi/Views/Shared/_ThemeStyles.cshtml
<!-- Fonts -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
<!-- Icons -->
<link href="~/vendor/nucleo/css/nucleo.css" rel="stylesheet" asp-append-version="true">
<link href="~/vendor/@@fortawesome/fontawesome-free/css/all.min.css" rel="stylesheet" asp-append-version="true">
<!-- Argon CSS -->
<link type="text/css" href="~/css/argon.min.css" rel="stylesheet" asp-append-version="true">